### PR TITLE
bumped axios version, ran npm install, pushing updates up

### PR DESCRIPTION
**Pull request by stbarillas**
## Description

Small PR
Bumping Axios version to address vulnerability

## Verify

- [x] Code runs without errors
- [ ] Tests pass with >=85% coverage

### CODE REVIEW

**Review by ronakshahlob — COMMENTED** [review]
I ran the tests on the PR and looks like the upgrade does have some breaking changes. Could you take a look. You should be able to see the breaking tests on the PR, let me know if not.

**Review by bamohan — COMMENTED** [review]
https://github.com/lob/lob-typescript-sdk/pull/275#pullrequestreview-1791268580

**Comment by comp615** [comment]
@bamohan @ronakshahlob Heya, I did an update to Steve's patch here. Due to how Axios changed packaging with cjs, Jest 27 is not able to understand that. We could add a hack/exception, but the easier solution is to just update that to Jest 29. So I did that and verified that npm test works locally now.

Thanks!

**Comment by prescottprue** [comment]
Any update here? It would be nice to remove vulnerabilities

**Comment by comp615** [comment]
> so you were able to test locally, no breaking changes from axios? if yes, good to merge.
> 
> I think we should also bump up this package's version from `"version": "1.3.3",` to `1.3.4`

All tests passed; we used the update in our code as well with no issues, however that's not to say we exercise all the functionality but seemed ok.

Feel free to bump the version as appropriate after merging so you can release :)

**Comment by QuentinLemCode** [comment]
Hello @stbarillas 
Can you merge this PR, please?
The axios version of this package raises a security issue on our repo

**Review by QuentinLemCode — APPROVED** [review]

**Comment by multigl** [comment]
also requesting this, axios is showing up in our vulnerability scans from @lob/lob-typescript-sdk

**Comment by juanfriss** [comment]
I think we need to bump up the package's version too from `1.3.3` to `1.3.4`

**Comment by juanfriss** [comment]
I will publish `1.3.4` in another PR and publish the new version shortly.

**Comment by juanfriss** [comment]
ended up publishing version `1.3.5`

**Pull request merged**
