### PR TITLE
GC-2560/bumps up version

### PR DESCRIPTION
**Pull request by juanfriss**
## Description

[GC-2560](https://lobsters.atlassian.net/browse/GC-2560)

Bumps version up after axios dependency was upgaded in https://github.com/lob/lob-typescript-sdk/pull/275

[GC-2560]: https://lobsters.atlassian.net/browse/GC-2560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by QuentinLemCode — APPROVED** [review]

**Comment by QuentinLemCode** [comment]
Jest v29 drop the support for Node V12
https://jest-archive-august-2023.netlify.app/docs/29.0/upgrading-to-jest29

You should drop the Node V12 support for this version

**Review by shannamurry — APPROVED** [review]

**Comment by QuentinLemCode** [comment]
@juanfriss Jest don't manage the error well
You can run the following command to see what make your tests fails : 
`npx jest -c jest.integrationConfig.js --detectOpenHandles` 

It looks like the requests aren't mocked
image

**Comment by juanfriss** [comment]
@QuentinLemCode yeah, there's a problem with the integration tests (which as you say, don't mock the API call).

All tests pass (`Tests: 93 passed, 93 total`), but there's something else that's breaking the coverage report and generating a failed result for the action:

```
Node.js v18.19.1
node:internal/child_process/serialization:159
    const string = JSONStringify(message) + '\n';
                   ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'socket' -> object with constructor 'Object'
    --- property '_httpMessage' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:159:20)
    at process.target._send (node:internal/child_process:845:17)
    at process.target.send (node:internal/child_process:745:19)
    at reportSuccess (/home/runner/work/lob-typescript-sdk/lob-typescript-sdk/node_modules/jest-worker/build/workers/processChild.js:82:11)
```

**Comment by juanfriss** [comment]
@QuentinLemCode running with `--detectOpenHandles` does throw much better and useful errors. Will check what's going on now.

**Comment by juanfriss** [comment]
all tests passed

**Pull request merged**
